"""OpenRouter API Client & Code Parser for NOVA Code Lab.

Provides unified OpenRouter API calls, prompt formatting, robust code cleaning,
multi-language syntax extraction, and error handling.
"""

import json
import os
import re
from typing import Dict, List, Optional, Tuple

from dotenv import load_dotenv
from openai import OpenAI

from backend.core.artifact_validator import is_placeholder_path

load_dotenv()

DEFAULT_MODEL = "openrouter/free"
REQUEST_TIMEOUT = 45.0


def get_openrouter_client() -> OpenAI:
    """Create and return an OpenAI-compatible client pointed at OpenRouter."""
    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        raise ValueError(
            "OPENROUTER_API_KEY is missing. "
            "Please copy .env.example to .env and set your OPENROUTER_API_KEY."
        )
    return OpenAI(
        api_key=api_key,
        base_url="https://openrouter.ai/api/v1",
        timeout=REQUEST_TIMEOUT,
        max_retries=1,
    )


def is_api_configured() -> bool:
    """Check if either NVIDIA_API_KEY or OPENROUTER_API_KEY is configured."""
    return bool(os.getenv("NVIDIA_API_KEY") or os.getenv("OPENROUTER_API_KEY"))


def get_current_model() -> str:
    """Return active provider and primary model."""
    from backend.core.llm.model_router import get_model_router
    router = get_model_router()
    provider, model = router.get_effective_provider_and_model("general")
    return f"{provider.name}: {model}"


def call_openrouter(
    messages: List[Dict[str, str]],
    system_prompt: Optional[str] = None,
    temperature: float = 0.2,
    max_retries: int = 2,
    role: str = "coder",
) -> str:
    """Execute completion request via ModelRouter with multi-provider resilience and role resolution."""
    from backend.core.llm.model_router import get_model_router
    router = get_model_router()
    return router.generate_text(
        role=role,
        messages=messages,
        system_prompt=system_prompt,
        temperature=temperature,
    )


def clean_code_block(raw_text: str, expected_lang: str = "") -> str:
    """Extract code from markdown code fences or raw text for ANY language."""
    text = raw_text.strip()
    if not text:
        return text

    # Try matching fenced code block ```lang ... ``` or ``` ... ```
    blocks = re.findall(r"```[a-zA-Z0-9_-]*\s*\n(.*?)```", text, re.DOTALL)
    if blocks:
        return blocks[-1].strip()

    # If text starts with ``` and ends with ```
    if text.startswith("```") and text.endswith("```"):
        lines = text.splitlines()
        if len(lines) >= 2:
            return "\n".join(lines[1:-1]).strip()

    return text


def parse_multi_file_response(raw_text: str, default_filename: Optional[str] = None) -> Dict[str, str]:
    """Parse multi-file responses generated by the LLM.

    Args:
        raw_text: Raw LLM output string.
        default_filename: Optional filename to map single-file or non-tagged responses to.
    """
    files: Dict[str, str] = {}

    file_sections = re.split(r"(?:###\s*FILE:|\bFILE:|\bFile:)\s*[`'\"]?([a-zA-Z0-9_\-./]+)[`'\"]?", raw_text)

    if len(file_sections) >= 3:
        for i in range(1, len(file_sections), 2):
            filepath = file_sections[i].strip()
            clean_fp = filepath.lstrip("./").lstrip("/")
            is_ph, _ = is_placeholder_path(clean_fp)
            if is_ph:
                continue
            content_block = file_sections[i + 1] if i + 1 < len(file_sections) else ""
            clean_content = clean_code_block(content_block)
            if clean_fp and clean_content:
                files[clean_fp] = clean_content

        if default_filename:
            target_clean = default_filename.strip().lstrip("./").lstrip("/")
            if target_clean not in files and not is_placeholder_path(target_clean)[0]:
                matched_key = next((k for k in files if k.endswith(target_clean) or target_clean.endswith(k)), None)
                if matched_key:
                    files[target_clean] = files[matched_key]

        if files:
            return files

    cleaned = clean_code_block(raw_text)
    if cleaned and default_filename:
        target_key = default_filename.strip().lstrip("./").lstrip("/")
        if not is_placeholder_path(target_key)[0]:
            files[target_key] = cleaned
    return files


def parse_json_response(raw_text: str) -> dict:
    """Extract and parse JSON from LLM output, handling preambles, safety strings, and markdown blocks."""
    if not raw_text or not raw_text.strip():
        return _fallback_json()

    text = raw_text.strip()

    # 1. Try code fence extraction
    blocks = re.findall(r"```(?:json)?\s*\n(.*?)```", text, re.DOTALL)
    if blocks:
        text = blocks[-1].strip()

    # 2. Extract substring between first '{' and last '}'
    start_dict = text.find("{")
    end_dict = text.rfind("}")

    if start_dict != -1 and end_dict != -1 and end_dict > start_dict:
        json_str = text[start_dict : end_dict + 1]
        try:
            return json.loads(json_str)
        except Exception:
            pass

    # 3. Extract substring between first '[' and last ']'
    start_arr = text.find("[")
    end_arr = text.rfind("]")
    if start_arr != -1 and end_arr != -1 and end_arr > start_arr:
        json_str = text[start_arr : end_arr + 1]
        try:
            res = json.loads(json_str)
            if isinstance(res, dict):
                return res
            elif isinstance(res, list):
                return {"items": res}
        except Exception:
            pass

    # 4. Try direct json.loads
    try:
        return json.loads(text)
    except Exception:
        pass

    # 5. Graceful Fallback if LLM output was prose or safety flag
    return _fallback_json()


def _fallback_json() -> dict:
    """Return a safe fallback architecture plan dict when LLM output lacks JSON."""
    return {
        "project_name": "SPIDY Project",
        "detected_language": "HTML/CSS/JS",
        "architecture_summary": "Interactive web application structure.",
        "tech_stack": ["HTML5", "CSS3", "JavaScript"],
        "is_complex": False,
        "clarifying_questions": [],
        "files": ["index.html", "style.css", "script.js", "README.md"],
        "tasks": [],
    }
